const ENV = {
    API_PROCESS_SNS_QUEUE: process.env.API_PROCESS_SNS_QUEUE,
    API_AUTHENTICATION_URL: process.env.API_AUTHENTICATION_URL,
    API_USER_URL: process.env.API_USER_URL,
    HEARTBEAT_INTERVAL: process.env.HEARTBEAT_INTERVAL,
    ENABLE_HEARTBEAT: process.env.ENABLE_HEARTBEAT
};
export default ENV;