export type TypographyVariant =
    | 'h1'
    | 'h2'
    | 'h3'
    | 'h4'
    | 'h5'
    | 'h6'
    | 'body1'
    | 'body1-thicker'
    | 'body1-link'
    | 'body1-caption'
    | 'body1-caption-link'
    | 'body2'
    | 'body2-thicker'
    | 'body2-link'
    | 'large-label'
    | 'medium-label'
    | 'small-label';
